replicas: 1
minimumMasterNodes: 1

resources:
  requests:
    cpu: 1000m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi

persistence:
  enabled: true
  labels:
    app: elasticsearch-master
    enabled: true
