kind: VirtualService
apiVersion: networking.istio.io/v1
metadata:
  name: kiali
  namespace: istio-system
spec:
  gateways:
    - cluster/gateway
  hosts:
    - kiali.anyflow.net
  http:
    - route:
        - destination:
            host: kiali.istio-system.svc.cluster.local
            port:
              number: 20001
# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#   name: kiali
#   namespace: istio-system
# spec:
#   parentRefs:
#     - name: gateway
#       namespace: cluster
#   hostnames:
#     - kiali.anyflow.net
#   rules:
#     - matches:
#         - path:
#             type: PathPrefix #Implementation-specific, PathPrefix, Exact
#             value: /
#       backendRefs:
#         - name: kiali
#           port: 20001
#     - filters:
#         - type: RequestRedirect
#           requestRedirect:
#             scheme: https
#             statusCode: 301
