apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kiali
  namespace: istio-system
spec:
  parentRefs:
    - name: public-gateway
      namespace: cluster
      kind: Gateway
  hostnames:
    - kiali.anyflow.net
  rules:
    - name: kiali-logout
      matches:
        - path:
            type: Exact
            value: /logout
      filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            add:
              - name: Set-Cookie
                value: agw_oidc_s_c40c87c1a4797d94=; Path=/; Max-Age=0; HttpOnly; SameSite=Lax; Secure
        - type: RequestRedirect
          requestRedirect:
            hostname: api.anyflow.net
            scheme: https
            path:
              type: ReplaceFullPath
              replaceFullPath: /auth/logout
            statusCode: 302
    - name: kiali-browser
      matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: kiali
          port: 20001
