apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kiali
  namespace: istio-system
spec:
  parentRefs:
    - name: default-gateway
      namespace: cluster
  hostnames:
    - kiali.anyflow.net
  rules:
    - matches:
        - path:
            type: PathPrefix #Implementation-specific, PathPrefix, Exact
            value: /
      backendRefs:
        - name: kiali
          port: 20001
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
