apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  labels:
    app: kiali-operator
    version: v1.84.0
  name: kiali
  namespace: istio-system
spec:
  auth:
    strategy: anonymous

  server:
    port: 20001
    web_fqdn: kiali.anyflow.net
    web_root: /
    observability:
      metrics:
        enabled: true
        port: 9090
      tracing:
        collector_type: otel
        collector_url: jaeger-collector.istio-system.svc.cluster.local:4317
        enabled: true
        otel:
          protocol: grpc

  external_services:
    istio:
      istiod_pod_monitoring_port: 15014
      istio_api_enabled: true
      istiod_deployment_name: istiod
      istio_identity_domain: svc.cluster.local
      component_status:
        components:
          - app_label: istiod
            is_core: true
            is_proxy: false
          # - app_label: istio-ingressgateway
          #   is_core: false
          # - app_label: istio-egressgateway
          #   is_core: false
        enabled: true
    prometheus:
      url: http://prometheus-server.cluster.svc.cluster.local:80
    grafana:
      enabled: true
      auth:
        type: basic
        username: admin
        password: admin
      dashboards:
        - name: "Istio Service Dashboard"
        - name: "Istio Workload Dashboard"
        - name: "Istio Mesh Dashboard"
        - name: "Istio Control Plane Dashboard"
        - name: "Istio Performance Dashboard"
        - name: "Istio Wasm Extension Dashboard"
      in_cluster_url: http://grafana.cluster.svc.cluster.local:80
      url: https://grafana.anyflow.net
    tracing:
      enabled: true
      in_cluster_url: http://jaeger-query.istio-system.svc.cluster.local:16686
      url: https://jaeger.anyflow.net
      use_grpc: false

  identity:
    cert_file: ""
    private_key_file: ""

  deployment:
    accessible_namespaces:
      - "**"
    view_only_mode: false
    namespace: istio-system
    image_pull_policy: Always
    replicas: 1
    resources:
      requests:
        cpu: "10m"
        memory: "64Mi"
      limits:
        memory: "1Gi"
    secret_name: "kiali"
    security_context: {}
    service_type: ClusterIP
    logger:
      log_level: "debug"
      log_format: "text"
      sampler_rate: "1"
      time_field_format: "2006-01-02T15:04:05Z07:00"
