# otel-otlp-collector service accounts are created automatically
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-otlp
  namespace: observability
  labels:
    app: otel-otlp-collector
spec:
  mode: deployment
  serviceAccount: otel-collector

  env:
    - name: GOMEMLIMIT
      value: 680MiB

  resources:
    requests:
      cpu: 500m
      memory: 1000Mi
    limits:
      cpu: 500m
      memory: 1000Mi

  autoscaler:
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilization: 60
    targetMemoryUtilization: 60

  podAnnotations:
    sidecar.istio.io/interceptionMode: TPROXY

  config:
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133

    service:
      extensions:
        - health_check

      telemetry:
        logs:
          level: info
        metrics:
          level: detailed

      pipelines:
        traces:
          receivers:
            - otlp
          processors:
            - memory_limiter
            - batch
          exporters:
            - debug
            - otlphttp/tempo

        logs:
          receivers:
            - otlp
          processors:
            - memory_limiter
            - batch
          exporters:
            - debug

        metrics:
          receivers:
            - otlp
          processors:
            - memory_limiter
            - batch
          exporters:
            - debug
            - prometheusremotewrite

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        send_batch_size: 8192
        send_batch_max_size: 0
        timeout: 5s
      memory_limiter:
        check_interval: 1s
        limit_percentage: 85
        spike_limit_percentage: 17

    exporters:
      debug:
        verbosity: basic
      prometheusremotewrite:
        endpoint: http://prometheus-server.observability.svc.cluster.local:80/api/v1/write
        target_info:
          enabled: false
        timeout: 30s
        remote_write_queue:
          enabled: true
          num_consumers: 5
          queue_size: 5000
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 300s
      otlphttp/tempo:
        endpoint: http://tempo.observability.svc.cluster.local:4318
