daemonset:
    enabled: true

config:
    flush: 1
    logLevel: info
    service: |
        [SERVICE]
            Flush           {{ .Values.config.flush }}
            Daemon          Off
            LogLevel        {{ .Values.config.logLevel }}
            Config_Watch    On
            HTTP_Server     On
            HTTP_Listen     0.0.0.0
            HTTP_Port       {{ .Values.containerPorts.http }}
            Parsers_File    /opt/bitnami/fluent-bit/conf/custom_parsers.conf
    inputs: |
        [INPUT]
            Name            tail
            Path            /var/log/pods/cluster_dockebi-tick*/*/*.log
            Tag             dockebi-tick

        [INPUT]
            Name            tail
            Path            /var/log/pods/cluster_dockebi-tock*/*/*.log
            Tag             dockebi-tock

        [INPUT]
            Name            tail
            Path            /var/log/pods/cluster_dockebi-storage*/*/*.log
            Tag             dockebi-storage

    filters: |
        [FILTER]
            Name            parser
            Match           *
            Key_Name        log
            Parser          general

        [FILTER]
            Name            lua
            Match           *
            Script          /opt/bitnami/fluent-bit/conf/general.lua
            Call            transform

        [FILTER]
            name            parser
            match           *
            Key_Name        message
            Parser          json

    outputs: |
        [OUTPUT]
            Name            stdout
            Match           *
            Format          json_lines
            json_date_key   timestamp

        [OUTPUT]
            Name            es
            Match           dockebi-tick
            Host            elasticsearch-es-http.cluster
            Port            9200
            Index           dockebi-tick
            HTTP_User       anyflow
            HTTP_Passwd     mycluster
            tls             Off
            tls.verify      Off
            Suppress_Type_Name On
            Logstash_Format On
            Logstash_Prefix dockebi-tick
            Time_Key        timestamp
            Replace_Dots    On
            Current_Time_Index On
            Trace_Output    On
            Trace_Error     On

        [OUTPUT]
            Name            es
            Match           dockebi-tock
            Host            elasticsearch-es-http.cluster
            Port            9200
            Index           dockebi-tock
            HTTP_User       anyflow
            HTTP_Passwd     mycluster
            tls             Off
            tls.verify      Off
            Suppress_Type_Name On
            Logstash_Format On
            Logstash_Prefix dockebi-tock
            Time_Key        timestamp
            Replace_Dots    On
            Current_Time_Index On
            Trace_Output    On
            Trace_Error     On

        [OUTPUT]
            Name            es
            Match           dockebi-storage
            Host            elasticsearch-es-http.cluster
            Port            9200
            Index           dockebi-storage
            HTTP_User       anyflow
            HTTP_Passwd     mycluster
            tls             Off
            tls.verify      Off
            Suppress_Type_Name On
            Logstash_Format On
            Logstash_Prefix dockebi-storage
            Time_Key        timestamp
            Replace_Dots    On
            Current_Time_Index On
            Trace_Output    On
            Trace_Error     On

    customParsers: |
        [PARSER]
            Name            general
            Format          regex
            Regex           ^(?<timestamp>[^ ]+) [^ ]+ [^ ] (?<message>.*)?
            Time_Key        timestamp

        [PARSER]
            Name            json
            Format          json
            Time_Key        timestamp

    extraFiles:
        general.lua: |
            function transform(tag, timestamp, record)
                if record["version"] ~= nil then -- Processed successfully in krakend.access.lua
                    return 0, timestamp, record
                end

                if json_formatted(record["message"]) then
                    if string.find(record["message"], "timestamp") then
                        return 0, timestamp, record
                    elseif string.gsub(record["message"], " ", "") == "{}" then
                        return 1, nil, {
                            ["timestamp"] = record["timestamp"]
                        }
                    else
                        return 1, nil, {
                            ["message"] = string.gsub(record["message"], "{", '{"timestamp":"' .. record["timestamp"] .. '",', 1)
                        }
                    end
                end

                return 1, nil, {
                    ["version"] = "1.0",
                    ["timestamp"] = record["timestamp"],
                    ["level"] = "INFO",
                    ["metadata"] = {
                        ["type"] = "general",
                    },
                    ["message"] = {
                        ["str"] = record["message"]
                    }
                }
            end

            function json_formatted(message)
                return message ~= nil
                    and string.sub(message, 1, 1) == "{"
                    and string.sub(message, -1) == "}"
            end

extraVolumeMounts:
    - name: config
      mountPath: /opt/bitnami/fluent-bit/conf/general.lua
      subPath: general.lua
