pilot:
  traceSampling: 100 # sampling percentage for tracing.
  resources:
    requests:
      cpu: 10m
      memory: 16Mi
    limits:
      cpu: 500m
      memory: 1024Mi

global:
  istioNamespace: istio-system

  proxy:
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
      limits:
        cpu: 250m
        memory: 64Mi

meshConfig:
  enableTracing: true
  # outboundTrafficPolicy:
  #   mode: REGISTRY_ONLY

  defaultConfig: # ProxyConfig.
    holdApplicationUntilProxyStarts: true
    tracing: {}
    # zipkin:
    #   address: jaeger-collector.istio-system.svc:9411 # jaeger collector address
    proxyMetadata:
      # Enable basic DNS proxying
      ISTIO_META_DNS_CAPTURE: "true"
      # Enable automatic address allocation, optional
      ISTIO_META_DNS_AUTO_ALLOCATE: "true"

  extensionProviders:
    - name: otelTrace
      opentelemetry:
        service: otel-otlp-collector.cluster.svc.cluster.local
        port: 4317
    - name: otelLog
      envoyOtelAls:
        service: otel-otlp-collector.cluster.svc.cluster.local
        port: 4317
        logFormat: # https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-ExtensionProvider-EnvoyOpenTelemetryLogProvider-LogFormat
          labels: # https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#config-access-log-format-dictionaries
            status: "%RESPONSE_CODE%"
            Body: "%LOCAL_REPLY_BODY%"
