apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secret
  namespace: cluster
type: Opaque
stringData:
  client-id: my-cluster-oauth2-proxy
  client-secret: REPLACE_ME
  cookie-secret: REPLACE_ME_BASE64_32_BYTES
  OAUTH2_PROXY_CLIENT_ID: my-cluster-oauth2-proxy
  OAUTH2_PROXY_CLIENT_SECRET: REPLACE_ME
  OAUTH2_PROXY_COOKIE_SECRET: REPLACE_ME_BASE64_32_BYTES
