apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api-logout
  namespace: cluster
spec:
  parentRefs:
    - name: public-gateway
      namespace: cluster
      kind: Gateway
  hostnames:
    - api.anyflow.net
  rules:
    - matches:
        - path:
            type: Exact
            value: /logout
      filters:
        - type: RequestRedirect
          requestRedirect:
            path:
              type: ReplaceFullPath
              replaceFullPath: /oauth2/sign_out?rd=https%3A%2F%2Fapi.anyflow.net%2Fauth%2Flogout
            statusCode: 302
