apiVersion: v1
kind: Secret
metadata:
  name: authelia-config
  namespace: cluster
type: Opaque
stringData:
  configuration.yml: |
    theme: auto

    server:
      address: tcp://0.0.0.0:9091/auth
      endpoints:
        authz:
          ext-authz:
            implementation: ExtAuthz

    log:
      level: info

    totp:
      issuer: anyflow.net

    authentication_backend:
      file:
        path: /config/users_database.yml

    access_control:
      default_policy: deny
      rules:
        - domain: api.anyflow.net
          resources:
            - '^/auth(?:$|/.*)'
          policy: bypass
        - domain: kagent.anyflow.net
          policy: one_factor
        - domain: agentgateway.anyflow.net
          policy: one_factor

    session:
      secret: REPLACE_ME
      cookies:
        - domain: anyflow.net
          authelia_url: https://api.anyflow.net/auth
          default_redirection_url: https://kagent.anyflow.net/

    storage:
      encryption_key: REPLACE_ME
      local:
        path: /data/db.sqlite3

    notifier:
      filesystem:
        filename: /data/notification.txt

    identity_validation:
      reset_password:
        jwt_secret: REPLACE_ME
  users_database.yml: |
    users:
      anyflow:
        disabled: false
        displayname: Anyflow
        password: REPLACE_WITH_ARGON2ID_HASH
        email: anyflow@anyflow.net
        groups:
          - admins
