apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 8.12.2
  http:
    tls:
      selfSignedCertificate: # Required to work in istio environment
        disabled: true
  podTemplate:
    spec:
      containers:
        - name: kibana
          env:
            - name: NODE_OPTIONS
              value: "--max-old-space-size=2048"
          resources:
            requests:
              cpu: 100m
              memory: 100m
            limits:
              cpu: 1000m
              memory: 1000Mi
  count: 1
  elasticsearchRef:
    name: elasticsearch
