apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
spec:
  storageClassName: ""
  claimRef:
    name: jenkins
    namespace: cluster
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 4Gi
  hostPath:
    path: /var/local-path-provisioner/jenkins
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - my-cluster-worker
