apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins
  namespace: cluster
spec:
  selector:
    matchLabels:
      app: jenkins
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: manual
