apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins
  namespace: cluster
spec:
  storageClassName: ""
  volumeName: jenkins
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
