agent:
  enabled: true

persistence:
  enabled: true
  existingClaim: jenkins # use manual volume provisioning

controller:
  podLabels:
    app: jenkins # for being identified by istio/kiali

  additionalPlugins:
    - ansicolor:1.0.4
    - docker-plugin:1.5

  ingress:
    enabled: false # refer httproute.yaml
