apiVersion: v1
kind: Namespace
metadata:
  name: cluster
  # labels:
  #   istio-injection: enabled
  #   istio.io/dataplane-mode: ambient
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  # labels:
  #   istio-injection: enabled
  #   istio.io/dataplane-mode: ambient
---
apiVersion: v1
kind: Namespace
metadata:
  name: opentelemetry
  # labels:
  #   istio-injection: enabled
  #   istio.io/dataplane-mode: ambient
---
apiVersion: v1
kind: Namespace
metadata:
  name: service
  # labels:
  #   istio-injection: enabled
  #   istio.io/dataplane-mode: ambient
