apiVersion: v1
kind: Namespace
metadata:
  name: cluster
  labels:
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: waypoint-cluster
    # istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: waypoint-istio-system
  #   istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: opentelemetry
  labels:
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: waypoint-opentelemetry
  #   istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: service
  labels:
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: waypoint-service
  #   istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-system
  labels:
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: waypoint-kube-system
  #   istio-injection: enabled
