apiVersion: v1
kind: Namespace
metadata:
  name: cluster
  labels:
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: waypoint-cluster
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: waypoint-istio-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: opentelemetry
  labels:
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: waypoint-opentelemetry
---
apiVersion: v1
kind: Namespace
metadata:
  name: service
  labels:
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: waypoint-service
---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-system
  labels:
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: waypoint-kube-system
