apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: default
  namespace: istio-system
spec:
  accessLogging:
    - providers:
        - name: envoy
        - name: otelLog
  tracing:
    - providers:
        - name: otelTrace
      randomSamplingPercentage: 100
      customTags:
        baggage:
          header:
            name: baggage
            defaultValue: "-"
        request_service:
          header:
            name: x-service-name
            defaultValue: "-"
        request_path:
          header:
            name: x-path-template
            defaultValue: "-"
        x-message-id:
          header:
            name: x-message-id
            defaultValue: "-"

  metrics:
    - providers:
        - name: prometheus
      overrides:
        - match:
            # metric: REQUEST_COUNT
            metric: ALL_METRICS # https://istio.io/latest/docs/reference/config/telemetry/#MetricSelector-IstioMetric
            mode: SERVER # https://istio.io/latest/docs/reference/config/telemetry/#WorkloadMode
          tagOverrides:
            request_method:
              value: request.method
            request_path:
              value: request.headers['x-path-template']
            request_service:
              value: request.headers['x-service-name']
            destination_port:
              value: destination.port
            request_protocol_version:
              value: request.protocol
  # metrics:
  #   - providers:
  #       - name: prometheus
  #     overrides:
  #       - match:
  #           metric: ALL_METRICS # https://istio.io/latest/docs/reference/config/telemetry/#MetricSelector-IstioMetric
  #           mode: CLIENT_AND_SERVER # https://istio.io/latest/docs/reference/config/telemetry/#WorkloadMode
  #         tagOverrides:
  #           request_method:
  #             value: request.method
  #           request_apigroup:
  #             value: request_apigroup
  #           request_path:
  #             value: request_path
# ---
# apiVersion: telemetry.istio.io/v1
# kind: Telemetry
# metadata:
#   name: waypoint
#   namespace: cluster
# spec:
#   targetRef:
#     name: waypoint
#     kind: Gateway
#     group: gateway.networking.k8s.io
#     # name: waypoint
#     # kind: Service
#     # group: core
#     # namespace: ""
#   accessLogging:
#     - providers:
#         - name: envoy
#         - name: otelLog
#   tracing:
#     - providers:
#         - name: otelTrace
#       randomSamplingPercentage: 100
# ---
# apiVersion: telemetry.istio.io/v1
# kind: Telemetry
# metadata:
#   name: waypoint
#   namespace: service
# spec:
#   targetRef:
#     name: waypoint
#     kind: Gateway
#     group: gateway.networking.k8s.io
#     # name: dockebi
#     # kind: Service
#     # group: core
#     # namespace: ""
#   accessLogging:
#     - providers:
#         - name: envoy
#         - name: otelLog
#   tracing:
#     - providers:
#         - name: otelTrace
#       randomSamplingPercentage: 100
