apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: openapi-endpoint-filter
  namespace: cluster
spec:
  selector:
    matchLabels:
      app: gateway
  url: anyflow/openapi-endpoint-filter:0.2.5
  imagePullPolicy: Always
  phase: STATS # Applies the filter before the istio.stats filter in the Envoy filter chain.
  failStrategy: FAIL_OPEN # Configures the filter to be non-critical; bypasses the filter on fatal errors.
  #  priority: 10
  match:
    - mode: SERVER
  pluginConfig:
    cacheSize: 5
    services:
      - name: dockebi
        paths:
          /dockebi/v1/stuff: {}
          /dockebi/v1/stuff/{id_}: {}
          /dockebi/v1/error/{status_code}: {}
          /dockebi/v1/health: {}
---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: openapi-endpoint-filter-dockebi
  namespace: cluster
spec:
  selector:
    matchLabels:
      app: gateway
  url: anyflow/openapi-endpoint-filter:0.2.5
  imagePullPolicy: Always
  phase: STATS # Applies the filter before the istio.stats filter in the Envoy filter chain.
  failStrategy: FAIL_OPEN # Configures the filter to be non-critical; bypasses the filter on fatal errors.
  #  priority: 10
  match:
    - mode: CLIENT
  pluginConfig:
    cacheSize: 5
    services:
      - name: dockebi
        paths:
          /v1/stuff: {}
          /v1/stuff/{id_}: {}
          /v1/error/{status_code}: {}
          /v1/health: {}
