apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: openapi-endpoint-filter-server
  namespace: cluster
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: public-gateway
  url: ghcr.io/anyflow/openapi-endpoint-filter:0.4.0
  imagePullPolicy: Always
  phase: STATS
  failStrategy: FAIL_OPEN
  match:
    - mode: SERVER
  pluginConfig:
    services:
      - name: dockebi
        paths:
          /dockebi/v1/stuff:
            get: {}
            post: {}
          /dockebi/v1/stuff/{id_}:
            get: {}
            put: {}
            delete: {}
          /dockebi/v1/error/400:
            get: {}
          /dockebi/v1/error/500:
            get: {}
          /dockebi/v1/health:
            get: {}
---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: openapi-endpoint-filter-client
  namespace: cluster
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: public-gateway
  url: ghcr.io/anyflow/openapi-endpoint-filter:0.4.0
  imagePullPolicy: Always
  phase: STATS
  failStrategy: FAIL_OPEN
  match:
    - mode: CLIENT
  pluginConfig:
    services:
      - name: dockebi
        paths:
          /v1/stuff:
            get: {}
            post: {}
          /v1/stuff/{id_}:
            get: {}
            put: {}
            delete: {}
          /v1/error/400:
            get: {}
          /v1/error/500:
            get: {}
          /v1/health:
            get: {}
