apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: baggage-filter
  namespace: cluster
spec:
  # selector:
  #   matchLabels:
  #     app: gateway
  targetRefs:
    - kind: Gateway
      group: gateway.networking.k8s.io
      name: gateway
  url: anyflow/baggage-filter:0.1.2
  imagePullPolicy: Always
  phase: STATS
  pluginConfig:
    headers:
      - "x-message-id"
