apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: gateway-endpoint-filter
  namespace: cluster
spec:
  targetRefs:
    - kind: Gateway
      group: gateway.networking.k8s.io
      name: gateway
  selector:
    matchLabels:
      app: gateway
  url: https://storage.googleapis.com/istio-build/proxy/attributegen-359dcd3a19f109c50e97517fe6b1e2676e870c4d.wasm
  imagePullPolicy: Always
  phase: AUTHN
  pluginConfig:
    attributes:
      - output_attribute: request_apigroup
        match:
          - value: "dockebi"
            condition: "request.url_path.matches('/dockebi/.*')"
      - output_attribute: request_path
        match:
          - value: "/dockebi/v1/stuff"
            condition: "request.url_path == '/dockebi/v1/stuff'"
          - value: "/dockebi/v1/stuff/{id_}"
            condition: "request.url_path.matches('/dockebi/v1/stuff/[A-Za-z0-9_.-]*')"
          - value: "/dockebi/v1/error/400"
            condition: "request.url_path == '/dockebi/v1/error/400'"
          - value: "/dockebi/v1/error/500"
            condition: "request.url_path == '/dockebi/v1/error/500'"
          - value: "/dockebi/v1/health"
            condition: "request.url_path == '/dockebi/v1/health'"
