service:
  type: NodePort
  nodePort: 30003

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 2Gi

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: kibana.anyflow.net
      paths:
        - path: /
  tls:
    - secretName: default-tls
      hosts:
        - kibana.anyflow.net
