apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: docserver
  namespace: service
spec:
  parentRefs:
    - name: public-gateway
      namespace: cluster
      kind: Gateway
  hostnames:
    - api.anyflow.net
  rules:
    - matches:
        - path:
            type: Exact
            value: /__openapi/openapi.yaml
      filters:
        - type: RequestRedirect
          requestRedirect:
            path:
              type: ReplaceFullPath
              replaceFullPath: /contents/apispec/openapi.yaml
            statusCode: 301
    - matches:
        - path:
            type: Exact
            value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            path:
              type: ReplaceFullPath
              replaceFullPath: /contents/apispec/swaggerui/index.html
            statusCode: 301
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: docserver
          port: 80
