apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jaeger
  namespace: observability
spec:
  parentRefs:
    - name: gateway
      namespace: cluster
  hostnames:
    - jaeger.anyflow.net
  rules:
    - matches:
        - path:
            type: PathPrefix #Implementation-specific, PathPrefix, Exact
            value: /
      backendRefs:
        - name: jaeger-query
          port: 16686
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
