collector:
  enabled: false

query:
  enabled: false

agent:
  enabled: false

provisionDataStore:
  cassandra: false
  elasticsearch: false
  kafka: false

storage:
  type: memory

allInOne:
  enabled: true
  samplingConfig: |-
    {
      "default_strategy": {
        "type": "probabilistic",
        "param": 1
      }
    }
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 256m
      memory: 128Mi
