#https://kubernetes.io/blog/2017/01/running-mongodb-on-kubernetes-with-statefulsets/

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 3
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongo
        image: mongo:5.0.7
        args:
        # - '--config'
        # - '/hostroot/mongo/mongod.conf'
        - '--bind_ip'
        - '0.0.0.0'
        - '--replSet'
        - 'anyflow-replset'
        - '--auth'
        - '--clusterAuthMode'
        - 'keyFile'
        - '--keyFile'
        - '/hostroot/mongo/keyfile'
        # - "--setParameter"
        # - "authenticationMechanisms=SCRAM-SHA-1"
        resources:
          limits:
            memory: '128Mi'
            cpu: '500m'
        ports:
        - containerPort: 27017
        volumeMounts:
          - name: hostroot
            mountPath: /hostroot
      volumes:
        - name: hostroot
          hostPath:
            path: /hostroot