apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: cluster
spec:
  project: default
  destination:
    namespace: cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true