yamlApplicationConfig:
  kafka:
    clusters:
      - name: yaml
        bootstrapServers: kafka.cluster.svc.cluster.local:9092
  auth:
    type: disabled
  management:
    health:
      ldap:
        enabled: false
ingress:
  enabled: true
  path: /
  host: kafkaui.anyflow.net
  ingressClassName: nginx
  tls:
    enabled: true
    secretName: default-tls
