apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana
  namespace: cluster
spec:
  parentRefs:
    - name: default-gateway
      namespace: cluster
  hostnames:
    - grafana.anyflow.net
  rules:
    - matches:
        - path:
            type: PathPrefix #Implementation-specific, PathPrefix, Exact
            value: /
      backendRefs:
        - name: grafana
          namespace: cluster
          port: 80
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
