adminUser: admin
adminPassword: admin

labels:
  app: grafana
  version: 10.4.0

podLabels:
  app: grafana
  version: 10.4.0

service:
  labels:
    app: grafana
    version: 10.4.0

env:
  GF_FEATURE_TOGGLES_ENABLE: traceToMetrics

ingress:
  enabled: false
  hosts:
    - grafana.anyflow.net
  ingressClassName: nginx
  path: /
  pathType: Prefix
  tls:
    - secretName: default-tls
      hosts:
        - grafana.anyflow.net

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.cluster.svc.cluster.local
        access: proxy
        isDefault: true
      # - name: Elasticsearch-otel-cluster
      #   type: elasticsearch
      #   url: http://elasticsearch-es-http.cluster.svc.cluster.local.:9200
      #   basicAuthUser: anyflow
      #   basicAuthPassword: mycluster
      #   access: proxy
      #   basicAuth: true
      #   isDefault: false
      #   jsonData:
      #     includeFrozen: false,
      #     index: otel-k8sobject-*
      #     logLevelField:
      #     logMessageField:
      #     maxConcurrentShardRequests: 5
      #     oauthPassThru: false
      #     sigV4Auth: false
      #     timeField: "@timestamp"
      #     tlsSkipVerify: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: kubernetes
        orgId: 1
        folder: kubernetes
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/kubernetes
      - name: istio
        orgId: 1
        folder: istio
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/istio
dashboards:
  kubernetes:
    kubernetes-views-global-dashboard:
      gnetId: 15757
      revision: 31
      datasource: Prometheus
    kubernetes-views-namespaces-dashboard:
      gnetId: 15758
      revision: 27
      datasource: Prometheus
    kubernetes-views-nodes-dashboard:
      gnetId: 15759
      revision: 19
      datasource: Prometheus
    kubernetes-views-pods-dashboard:
      gnetId: 15760
      revision: 22
      datasource: Prometheus
