adminUser: admin
adminPassword: admin

labels:
  app: grafana
  version: latest

podLabels:
  app: grafana
  version: latest

service:
  labels:
    app: grafana
    version: latest

env:
  GF_FEATURE_TOGGLES_ENABLE: traceToMetrics

ingress:
  enabled: false
  hosts:
    - grafana.anyflow.net
  ingressClassName: nginx
  path: /
  pathType: Prefix
  tls:
    - secretName: default-tls
      hosts:
        - grafana.anyflow.net

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.observability.svc.cluster.local
        access: proxy
        isDefault: true
      - name: Jaeger
        type: jaeger
        url: http://jaeger-query.observability.svc.cluster.local:16686
        access: proxy
        jsonData:
          tracesToLogsV2:
            datasourceUid: "Elasticsearch"
            filterByTraceID: true
            filterBySpanID: true
      - name: Elasticsearch
        type: elasticsearch
        url: http://elasticsearch-es-internal-http.cluster.svc.cluster.local:9200
        access: proxy
        basicAuth: true
        basicAuthUser: anyflow
        secureJsonData:
          basicAuthPassword: mycluster
        jsonData:
          esVersion: 7
          timeField: "@timestamp"
          maxConcurrentShardRequests: 256
          interval: Daily
          logMessageField: message
          logLevelField: level

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: kubernetes
        orgId: 1
        folder: Kubernetes
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/kubernetes
      - name: istio
        orgId: 1
        folder: Istio
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/istio
dashboards:
  kubernetes:
    kubernetes-views-global-dashboard:
      gnetId: 15757
      revision: 31
      datasource: Prometheus
    kubernetes-views-namespaces-dashboard:
      gnetId: 15758
      revision: 27
      datasource: Prometheus
    kubernetes-views-nodes-dashboard:
      gnetId: 15759
      revision: 19
      datasource: Prometheus
    kubernetes-views-pods-dashboard:
      gnetId: 15760
      revision: 22
      datasource: Prometheus
  istio:
    istio-mesh-dashboard:
      gnetId: 7639
      revision: 218
      datasource: Prometheus
    istio-service-dashboard:
      gnetId: 7636
      revision: 218
      datasource: Prometheus
    istio-workload-dashboard:
      gnetId: 7630
      revision: 218
      datasource: Prometheus
    istio-performance-dashboard:
      gnetId: 11829
      revision: 218
      datasource: Prometheus
    istio-controlplane-dashboard:
      gnetId: 7645
      revision: 218
      datasource: Prometheus
    istio-wasmextension-dashboard:
      gnetId: 13277
      revision: 175
      datasource: Prometheus
