apiVersion: v1
kind: Service
metadata:
  name: kagent-a2a
  namespace: kagent
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kagent
    app.kubernetes.io/instance: kagent
    app.kubernetes.io/component: controller
  ports:
    - name: a2a
      port: 8083
      targetPort: 8083
      protocol: TCP
      appProtocol: kgateway.dev/a2a
---
apiVersion: v1
kind: Service
metadata:
  name: kagent-mcp
  namespace: kagent
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kagent
    app.kubernetes.io/instance: kagent
    app.kubernetes.io/component: controller
  ports:
    - name: mcp
      port: 8083
      targetPort: 8083
      protocol: TCP
      appProtocol: agentgateway.dev/mcp
