commonMetaLabels:
  app: prometheus
  version: latest

server:
  podLabels:

  resources:
    requests:
      cpu: 10m
      memory: 10Mi
    limits:
      cpu: 1000m
      memory: 1Gi

  extraFlags:
    - web.enable-lifecycle #default
    - web.enable-remote-write-receiver # allow remote write
    - enable-feature=exemplar-storage # allow exemplar storage

  extraArgs:
    log.level: info

  retention: 1h

  replicaCount: 1
  statefulSet:
    enabled: false
  persistentVolume:
    enabled: false
    storageClass: "standard"
  ingress:
    enabled: false

prometheus-node-exporter:
  enabled: true

kube-state-metrics:
  enabled: true
  metricLabelsAllowlist:
    - pods=[*]
    - namespaces=[*]
    - nodes=[*]
    - deployments=[*]
    - daemonsets=[*]
    - statefulsets=[*]
    - replicasets=[*]
    - replicationcontrollers=[*]
    - jobs=[*]
    - cronjobs=[*]
    - services=[*]
    - ingresses=[*]
    - horizontalpodautoscalers=[*]
    - persistentvolumes=[*]
    - persistentvolumeclaims=[*]

prometheus-pushgateway:
  enabled: false

alertmanager:
  enabled: false

serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: prometheus-self
        static_configs:
          - targets:
              - localhost:9090
      # - job_name: otel-prometheus-collector # only collect metrics from otel-collector
      #   static_configs:
      #     - targets:
      #         - otel-prometheus-collector.cluster.svc.cluster.local.:9090
