server:
  podLabels:
    app: prometheus
    version: latest

  resources:
    requests:
      cpu: 10m
      memory: 10Mi
    limits:
      cpu: 1000m
      memory: 1Gi

  extraFlags:
    - web.enable-lifecycle #default
    - web.enable-remote-write-receiver # allow remote write
    - enable-feature=otlp-write-receiver # allow OTLP receiver
    - enable-feature=exemplar-storage # allow exemplar storage

  extraArgs:
    log.level: debug

  replicaCount: 1
  statefulSet:
    enabled: false
  persistentVolume:
    enabled: false
    storageClass: "standard"
  ingress:
    enabled: false

prometheus-node-exporter:
  enabled: true

prometheus-pushgateway:
  enabled: false

alertmanager:
  enabled: false

kube-state-metrics:
  enabled: true

serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
              - localhost:9090
      # - job_name: otel-prometheus-collector # only collect metrics from otel-collector
      #   static_configs:
      #     - targets:
      #         - otel-prometheus-collector.cluster.svc.cluster.local.:9090
