apiVersion: v1
kind: Service
metadata:
  name: agentgateway-admin
  namespace: agentgateway-system
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: agentgateway-proxy
    app.kubernetes.io/name: agentgateway-proxy
    gateway.networking.k8s.io/gateway-name: agentgateway-proxy
  ports:
    - name: http-admin
      port: 15001
      targetPort: 15002
      protocol: TCP
      appProtocol: HTTP
