apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry
  namespace: cluster
spec:
  storageClassName: ""
  volumeName: docker-registry
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
