apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: default
spec:
  description: Default project for all applications
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
