dex:
  enabled: false

notifications:
  enabled: false

applicationSet:
  enabled: true
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

redis:
  enabled: true
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  persistence:
    enabled: false
  usePassword: false

configs:
  params:
    server.insecure: true # Prevent recursive https requesting when using httproute instead of ingress
    server.enable.redis: true

  service:
    type: ClusterIP
    servicePortHttp: 80

  ingress:
    enabled: false

  secret:
    argocdServerAdminPassword: "$2y$10$awrl2wTQ0HYLbGtYx9Bs4OOsyFW48DW9WZn6hnFiTiQuTA.nBEOWS"

server:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

  extension:
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 32Mi

controller:
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

repoServer:
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 32Mi

  volumeMounts:
    - name: ssh-key
      mountPath: /app/config/my-ssh
      readOnly: true
  volumes:
    - name: ssh-key
      secret:
        secretName: git-secret
